services:
  advancedtaskmanager:
    image: advancedtaskmanager:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Europe/Madrid
    volumes:
      - .:/app/data/